#include 'protheus.ch'
#include 'parmtype.ch'

user function cbQryMrkBrw(cFields, cFilOrig)
	local cFiltro as character
	default cFilOrig := '03'
	cFiltro := ""
	cFiltro += " SELECT "
	cFiltro += cFields
	cFiltro += " FROM "+ retSqlName('SC5') + " SC5 "
	cFiltro += " WHERE "
	cFiltro += " SC5.C5_FILIAL + SC5.C5_NUM  IN ( "
	cFiltro += "  SELECT " 
	cFiltro += " 	DISTINCT SC5.C5_FILIAL + SC9.C9_PEDIDO AS [CHAVE] "
	cFiltro += " FROM " + RetSqlName('SC9') + " SC9 "
	cFiltro += " INNER JOIN " +  RetSqlName('SC6') + " SC6  WITH (NOLOCK) " 
	cFiltro += " ON SC9.C9_FILIAL		= SC6.C6_FILIAL "
	cFiltro += " AND SC9.C9_PEDIDO		= SC6.C6_NUM "
	cFiltro += " AND SC9.C9_ITEM		= SC6.C6_ITEM " 
	cFiltro += " AND SC9.C9_PRODUTO		= SC6.C6_PRODUTO  "
	cFiltro += " AND SC6.R_E_C_N_O_		= SC6.R_E_C_N_O_  "
	cFiltro += " AND SC9.D_E_L_E_T_		= SC6.D_E_L_E_T_  "
	cFiltro += " INNER JOIN " + RetSqlName('SC5') + " SC5 WITH (NOLOCK) " 
	cFiltro += " ON  SC6.C6_FILIAL		= SC5.C5_FILIAL " 
	cFiltro += " AND SC6.C6_NUM			= SC5.C5_NUM " 
	cFiltro += " AND SC5.R_E_C_N_O_		= SC5.R_E_C_N_O_ " 
	cFiltro += " AND SC6.D_E_L_E_T_		= SC5.D_E_L_E_T_ " 
	cFiltro += " INNER JOIN " +  RetSqlName('SA1') + " SA1  WITH (NOLOCK) "
	cFiltro += " ON '" + xFilial('SA1') + "' = SA1.A1_FILIAL "
	cFiltro += " AND SC5.C5_CLIENTE	= SA1.A1_COD "
	cFiltro += " AND SC5.C5_LOJACLI	= SA1.A1_LOJA "
	cFiltro += " AND SC5.D_E_L_E_T_	= SA1.D_E_L_E_T_ "
	cFiltro += " INNER JOIN " + RetSqlName('SB1') + " SB1 WITH (NOLOCK) " 
	cFiltro += " ON ''					= SB1.B1_FILIAL "
	cFiltro += " AND SC9.C9_PRODUTO		= SB1.B1_COD "
	cFiltro += " AND SC9.D_E_L_E_T_		= SB1.D_E_L_E_T_ "
	cFiltro += " INNER JOIN " + RetSqlName('SF4') + " SF4 WITH (NOLOCK) "
	cFiltro += " ON ''					= SF4.F4_FILIAL "
	cFiltro += " AND SC6.C6_TES			= SF4.F4_CODIGO "
	cFiltro += " AND SC6.D_E_L_E_T_		= SF4.D_E_L_E_T_ "
	cFiltro += " WHERE " 
	cFiltro += " SC9.C9_FILIAL IN ('" + cFilOrig + "') " 
	cFiltro += " AND SC9.C9_PEDIDO NOT IN(' ') " 
	cFiltro += " AND SC9.C9_BLCRED IN (' ') " 
	cFiltro += " AND SC9.C9_BLEST  IN ('02') " 
	cFiltro += " AND SC9.C9_SERIENF NOT IN ('U') " 
	cFiltro += " AND SC5.C5_LIBEROK = 'S' "
	cFiltro += " AND C5_NOTA = '' "
	cFiltro += " AND C5_TIPO = 'N' "
	cFiltro += " AND C5_X_IDVEN = '' "
	cFiltro += " AND SC6.C6_BLQ <> 'R' "
	cFiltro += " AND SF4.F4_ESTOQUE = 'S' "
	cFiltro += " AND SB1.B1_TIPO = 'PA' "
	cFiltro += " AND SC9.D_E_L_E_T_ = '' "
	cFiltro += " ) " 
return(cFiltro)
