#include 'protheus.ch'
#include 'parmtype.ch'

static function qryMovs(cOpc, cDtIni, cDtFim, lInd)
    local cQry      := ""
    default cOpc    := "PR"
    default lInd    := .F.

    cQry += " SELECT SD3.D3_COD AS [PRODUTO],  "
    cQry += " SD3.D3_QUANT AS [QTD],  "
    cQry += " SD3.D3_LOCAL AS [ARMZ],  "
    cQry += " SD3.D3_EMISSAO AS [EMISSAO], "
    cQry += " SD3.D3_OP AS [OP], "
    cQry += " SC2.C2_EMISSAO AS [EMISSAO_OP], "
    cQry += " SC2.C2_DATRF AS [ENCERRA_OP], "
    cQry += " SD3.D3_HIST AS [HIST], "
    cQry += " SD3.D3_USUARIO AS [USUARIO], "
    cQry += " (SD3.D3_QUANT * SB1.B1_PESCOB) AS [COBRE], "
    cQry += " (SD3.D3_QUANT * SB1.B1_PESPVC) AS [PVC], "
    cQry += " SD3.D3_NUMSEQ AS [SEQ],  "
    cQry += " SD3.R_E_C_N_O_ AS [REC], "
    cQry += " SD3.D3_CF AS [TPMOV], "
    cQry += " SD1.D1_DOC AS [DOC] "
    cQry += " FROM SD3010 SD3 "
    cQry += " INNER JOIN SC2010 SC2 ON SC2.C2_FILIAL = SD3.D3_FILIAL "
    cQry += " 					AND SC2.C2_NUM+SC2.C2_ITEM+SC2.C2_SEQUEN = SD3.D3_OP "
    cQry += " 					AND SC2.D_E_L_E_T_ = SD3.D_E_L_E_T_ "
    cQry += " INNER JOIN SB1010 SB1 ON SD3.D3_COD = SB1.B1_COD "
    cQry += " 					AND SD3.D_E_L_E_T_ = SB1.D_E_L_E_T_ "
    cQry += " LEFT JOIN SD1010 SD1 ON SD3.D3_FILIAL = SD1.D1_FILIAL "
    cQry += " 					AND SD3.D3_OP = SD1.D1_OP "
    cQry += " 					AND SD3.D3_NUMSEQ = SD1.D1_NUMSEQ "
    cQry += " 					AND SD3.D_E_L_E_T_ = SD1.D_E_L_E_T_ "
    cQry += " WHERE SD3.D3_FILIAL = '" + xFilial("SD3") + "' "
    cQry += " AND SD3.D3_EMISSAO BETWEEN '" + cDtIni + "' AND '" + cDtFim + "' "
    cQry += " AND SD3.D3_OP <> '' "
    if cOpc == "PR"
        cQry += " AND SD3.D3_CF = 'PR0' "
    elseif cOpc == "RE"
        cQry += " AND SD3.D3_CF IN ('RE0','RE5') "
    else
        cQry += " AND SD3.D3_CF = 'DE0' "
    endif
    cQry += " AND SD3.D3_OP NOT IN ( "
    cQry += " 						SELECT SSD3.D3_OP "
    cQry += " 						FROM SD3010 SSD3 "
    cQry += " 						WHERE SSD3.D3_FILIAL = SD3.D3_FILIAL "
    cQry += " 						AND SSD3.D3_EMISSAO BETWEEN '" + cDtIni + "' AND '" + cDtFim + "' "
    cQry += " 						AND SSD3.D3_OP <> '' "
    if cOpc == "RE"
        cQry += " 					AND SSD3.D3_CF = 'PR0' "
    else
        cQry += " 					AND SSD3.D3_CF IN ('RE0','RE5') "
    endif
    cQry += " 						AND SSD3.D3_TIPO NOT IN ('SV','MOD') "
    cQry += " 						AND SSD3.D_E_L_E_T_ = SD3.D_E_L_E_T_ "
    cQry += " 						AND SSD3.D3_ESTORNO <> 'S' "
    cQry += " ) "
    if !lInd
        cQry += " AND SD1.D1_DOC IS NULL "
    else
        cQry += " AND SD1.D1_DOC IS NOT NULL "
    endif
    cQry += " AND SD3.D_E_L_E_T_ = '' "
    cQry += " AND SD3.D3_ESTORNO <> 'S' "
    cQry += " ORDER BY SD3.D3_EMISSAO, SD3.D3_COD "
return(cQry)

static function qryDevs(cDtIni, cDtFim)
    local cQry      := ""
    cQry += " SELECT TEMP.PRODUTO AS [PRODUTO], "
    cQry += " TEMP.OP AS [OP], "
    cQry += " TEMP.QTD AS [QTD_DEV], "
    cQry += " TEMP.QTD_REQ AS [QTD_REQ], "
    cQry += " TEMP.EMISSAO_OP AS [EMISSAO_OP], "
    cQry += " TEMP.ENCERRAMENTO_OP AS [ENCERRA_OP] "
    cQry += " FROM ( "
    cQry += " 		SELECT SD3.D3_COD AS [PRODUTO],  "
    cQry += " 		SUM(SD3.D3_QUANT) AS [QTD],  "
    cQry += " 		ISNULL(( "
    cQry += " 			SELECT SUM(SSD3.D3_QUANT) "
    cQry += " 			FROM SD3010 SSD3 "
    cQry += " 			WHERE SSD3.D3_FILIAL = SD3.D3_FILIAL "
    cQry += " 			AND SSD3.D3_EMISSAO BETWEEN '" + cDtIni + "' AND '" + cDtFim + "' "
    cQry += " 			AND SSD3.D3_OP = SD3.D3_OP "
    cQry += " 			AND SSD3.D3_COD = SD3.D3_COD "
    cQry += " 			AND SSD3.D3_CF IN ('RE0','RE5') "
    cQry += " 			AND SSD3.D3_TIPO NOT IN ('SV','MOD') "
    cQry += " 			AND SSD3.D_E_L_E_T_ = SD3.D_E_L_E_T_ "
    cQry += " 			AND SSD3.D3_ESTORNO <> 'S' "
    cQry += " 		),0) AS [QTD_REQ], "
    cQry += " 		SD3.D3_OP AS [OP], "
    cQry += " 		SC2.C2_EMISSAO AS [EMISSAO_OP], "
    cQry += " 		SC2.C2_DATRF AS [ENCERRAMENTO_OP] "
    cQry += " 		FROM SD3010 SD3 "
    cQry += " 		INNER JOIN SC2010 SC2 ON SC2.C2_FILIAL = SD3.D3_FILIAL "
    cQry += " 							AND SC2.C2_NUM+SC2.C2_ITEM+SC2.C2_SEQUEN = SD3.D3_OP "
    cQry += " 							AND SC2.D_E_L_E_T_ = SD3.D_E_L_E_T_ "
    cQry += " 		WHERE SD3.D3_FILIAL = '" + xFilial("SD3") + "' "
    cQry += " 		AND SD3.D3_EMISSAO BETWEEN '" + cDtIni + "' AND '" + cDtFim + "' "
    cQry += " 		AND SD3.D3_OP <> '' "
    cQry += " 		AND SD3.D3_CF = 'DE0' "
    cQry += " 		AND SD3.D_E_L_E_T_ = '' "
    cQry += " 		AND SD3.D3_ESTORNO <> 'S' "
    cQry += " 		GROUP BY SD3.D3_FILIAL, SD3.D3_COD, SD3.D3_OP, SC2.C2_EMISSAO, SC2.C2_DATRF, SD3.D_E_L_E_T_ "
    cQry += " ) AS TEMP "
    cQry += " WHERE TEMP.QTD > TEMP.QTD_REQ "
    cQry += " ORDER BY TEMP.PRODUTO "
return(cQry)

static function qryMovPosProd(cDtIni, cDtFim)
    local cQry      := ""

    cQry += " SELECT SD3.D3_COD AS [PRODUTO], "
    cQry += " SD3.D3_QUANT AS [QTD], "
    cQry += " SD3.D3_OP AS [OP], "
    cQry += " SD3.D3_EMISSAO AS [EMISSAO], "
    cQry += "  ( "
    cQry += " 						SELECT MAX(D3.D3_EMISSAO) "
    cQry += " 						FROM SD3010 D3 "
    cQry += " 						WHERE D3.D3_FILIAL = SD3.D3_FILIAL "
    cQry += " 						AND D3.D3_OP = SD3.D3_OP "
    cQry += " 						AND D3.D3_EMISSAO BETWEEN '" + cDtIni + "' AND '" + cDtFim + "' "
    cQry += " 						AND D3.D3_CF IN ('PR0') "
    cQry += " 						AND D3.D_E_L_E_T_ = SD3.D_E_L_E_T_ "
    cQry += " 						AND D3.D3_ESTORNO = SD3.D3_ESTORNO "
    cQry += " ) AS [MAX_EMISS] "
    cQry += " FROM SD3010 SD3 "
    cQry += " WHERE SD3.D3_FILIAL = '" + xFilial("SD3") + "' "
    cQry += " AND SD3.D3_CF NOT IN ('PR0') "
    cQry += " AND SD3.D3_OP <> '' "
    cQry += " AND SD3.D3_EMISSAO BETWEEN '" + cDtIni + "' AND '" + cDtFim + "' "
    cQry += " AND SD3.D3_EMISSAO > ( "
    cQry += " 						SELECT MAX(D3.D3_EMISSAO) "
    cQry += " 						FROM SD3010 D3 "
    cQry += " 						WHERE D3.D3_FILIAL = SD3.D3_FILIAL "
    cQry += " 						AND D3.D3_OP = SD3.D3_OP "
    cQry += " 						AND D3.D3_CF IN ('PR0') "
    cQry += " 						AND D3.D_E_L_E_T_ = SD3.D_E_L_E_T_ "
    cQry += " 						AND D3.D3_ESTORNO = SD3.D3_ESTORNO "
    cQry += " ) "
    cQry += " AND SD3.D3_ESTORNO <> 'S' "
    cQry += " AND SD3.D_E_L_E_T_ = '' "
    cQry += " ORDER BY SD3.D3_EMISSAO, SD3.D3_COD "
return(cQry)

static function qryMovPosOP(cOpc, cDtIni, cDtFim)
    local cQry      := ""
    default cOpc    := "INI"

    cQry += " SELECT SD3.D3_COD AS [PRODUTO],  "
    cQry += " SD3.D3_QUANT AS [QTD],  "
    cQry += " SD3.D3_LOCAL AS [ARMZ],  "
    cQry += " SD3.D3_EMISSAO AS [EMISSAO], "
    cQry += " SD3.D3_OP AS [OP], "
    cQry += " SC2.C2_EMISSAO AS [EMISSAO_OP], "
    cQry += " SC2.C2_DATRF AS [ENCERRA_OP], "
    cQry += " SD3.D3_HIST AS [HIST], "
    cQry += " SD3.D3_USUARIO AS [USUARIO], "
    cQry += " (SD3.D3_QUANT * SB1.B1_PESCOB) AS [COBRE], "
    cQry += " (SD3.D3_QUANT * SB1.B1_PESPVC) AS [PVC], "
    cQry += " SD3.D3_NUMSEQ AS [SEQ],  "
    cQry += " SD3.R_E_C_N_O_ AS [REC], "
    cQry += " SD3.D3_CF AS [TPMOV], "
    cQry += " SD3.D3_DOC AS [DOC] "
    cQry += " FROM SC2010 SC2 "
    cQry += " INNER JOIN SD3010 SD3 ON SC2.C2_FILIAL = SD3.D3_FILIAL "
    cQry += " 					AND SC2.C2_NUM+SC2.C2_ITEM+SC2.C2_SEQUEN = SD3.D3_OP "
    cQry += " 					AND SC2.D_E_L_E_T_ = SD3.D_E_L_E_T_ "
    cQry += " INNER JOIN SB1010 SB1 ON SD3.D3_COD = SB1.B1_COD "
    cQry += " 					AND SD3.D_E_L_E_T_ = SB1.D_E_L_E_T_ "
    cQry += " WHERE SC2.C2_FILIAL = '" + xFilial("SD3") + "' "
    if cOpc == "INI"
        cQry += " AND SC2.C2_EMISSAO > SD3.D3_EMISSAO "
    else
        cQry += " AND SC2.C2_DATRF < SD3.D3_EMISSAO "
        cQry += " AND SC2.C2_DATRF <> '' "
    endif
    cQry += " AND SD3.D3_ESTORNO <> 'S' "
    cQry += " AND SD3.D3_EMISSAO BETWEEN '" + cDtIni + "' AND '" + cDtFim + "' "
    cQry += " AND SC2.D_E_L_E_T_ = '' "
    cQry += " ORDER BY SD3.D3_EMISSAO, SD3.D3_COD "
return(cQry)

static function qryMOD(cDtIni, cDtFim)
    local cQry := ""

    cQry += " SELECT SD3.D3_COD AS [PRODUTO], "
    cQry += " SD3.D3_DOC AS [DOC], "
    cQry += " SD3.D3_QUANT AS [QTD], "
    cQry += " SD3.D3_HIST AS [HIST], "
    cQry += " SD3.D3_OP AS [OP], "
    cQry += " SD3.D3_EMISSAO AS [EMISSAO], "
    cQry += " SD3.D3_ZZLOTE AS [LOTE], "
    cQry += " SD3.D3_ZZUNMOV AS [UNMOV], "
    cQry += " SUBSTRING(SD3.D3_HIST, 9,15) AS [RECURSO], "
    cQry += " SC2.R_E_C_N_O_ AS [REC_SC2] "
    cQry += " FROM " + RetSqlName('SD3') + " SD3 "
    cQry += " INNER JOIN " + RetSqlName('SC2') + " SC2 ON SD3.D3_FILIAL		= SC2.C2_FILIAL "
    cQry += " 						AND SD3.D3_OP		= SC2.C2_NUM + SC2.C2_ITEM + SC2.C2_SEQUEN "
    cQry += " 						AND SD3.D_E_L_E_T_	= SC2.D_E_L_E_T_ "
    cQry += " WHERE SD3.D3_FILIAL = '" + xFilial("SD3") + "' "
    cQry += " AND SD3.D3_EMISSAO >= '" + cDtIni + "' "
    cQry += " AND SD3.D3_EMISSAO <= '" + cDtFim + "' "
    cQry += " AND SD3.D3_DOC NOT IN (					 "
    cQry += " 	    SELECT SSD3.D3_DOC "
    cQry += " 	    FROM " + RetSqlName('SD3') + " SSD3 "
    cQry += " 	    WHERE SSD3.D3_FILIAL = SD3.D3_FILIAL "
    cQry += " 	    AND SSD3.D3_EMISSAO >= '" + cDtIni + "' "
    cQry += " 	    AND SSD3.D3_EMISSAO <= '" + cDtFim + "' "
    cQry += " 	    AND SSD3.D3_DOC = SD3.D3_DOC "
    cQry += " 	    AND SSD3.D3_CF = 'RE0' "
    cQry += " 	    AND SSD3.D3_TIPO = 'MO' "
    cQry += " 	    AND SSD3.D_E_L_E_T_ = SD3.D_E_L_E_T_ "
    cQry += " ) "
    cQry += " AND SD3.D3_CF = 'PR0' "
    cQry += " AND SD3.D3_HIST <> '' "
    cQry += " AND SD3.D3_ESTORNO <> 'S' "
    cQry += " AND SD3.D_E_L_E_T_ = '' "
    cQry += " AND ISNUMERIC(SD3.D3_DOC) = 1 "
    cQry += " ORDER BY SD3.D3_EMISSAO, SD3.D3_DOC "
return(cQry)

static function qryHasRec(cTable)
    local cQry := ""

    cQry += " SELECT * "
    cQry += " FROM " + cTable
    cQry += " AS TEMP "
    cQry += " WHERE TEMP.D_E_L_E_T_ = '' "
return(cQry)

static function qryPAR(cDtIni, cDtFim)
    local cQry := ""

    cQry += " SELECT SD3.D3_COD AS [PRODUTO], "
    cQry += " SD3.D3_QUANT AS [QUANT], "
    cQry += " SD3.D3_LOCAL AS [ARMZ], "
    cQry += " SD3.D3_EMISSAO AS [EMISSAO], "
    cQry += " SD3.D3_OP AS [OP], "
    cQry += " SD3.D3_HIST AS [HIST], "
    cQry += " SD3.D3_USUARIO AS [USUARIO], "
    cQry += " (SD3.D3_QUANT * SB1.B1_PESPVC) AS [PVC], "
    cQry += " (SD3.D3_QUANT * SB1.B1_PESCOB) AS [COBRE], "
    cQry += " SD3.D3_CF AS [TPMOV], "
    cQry += " SD3.D3_DOC AS [DOC], "
    cQry += " SD3.D3_NUMSEQ AS [SEQ], "
    cQry += " SD3.R_E_C_N_O_ AS [REC] "
    cQry += " FROM " + RetSqlName('SD3') + " SD3 "
    cQry += " INNER JOIN " + RetSqlName('SB1') + " SB1 ON SD3.D3_COD = SB1.B1_COD AND SD3.D_E_L_E_T_ = SB1.D_E_L_E_T_ "
    cQry += " WHERE SD3.D3_FILIAL = '" + xFilial("SD3") + "' "
    cQry += " AND SD3.D3_EMISSAO >= '" + cDtIni + "' "
    cQry += " AND SD3.D3_EMISSAO <= '" + cDtFim + "' "
    cQry += " AND SD3.D3_CF IN ('RE7','RE4') "
    cQry += " AND SD3.D3_NUMSEQ NOT IN ( "
    cQry += " 						SELECT SSD3.D3_NUMSEQ "
    cQry += " 						FROM " + RetSqlName('SD3') + " SSD3 "
    cQry += " 						WHERE SSD3.D3_FILIAL = SD3.D3_FILIAL "
    cQry += " 						AND SSD3.D3_EMISSAO >= '" + cDtIni + "' "
    cQry += " 						AND SSD3.D3_EMISSAO <= '" + cDtFim + "' "
    cQry += " 						AND SSD3.D3_CF IN ('DE7','DE4') "
    cQry += " 						AND SSD3.D3_ESTORNO = SD3.D3_ESTORNO "
    cQry += " 						AND SSD3.D_E_L_E_T_ = SD3.D_E_L_E_T_  "
    cQry += " ) "
    cQry += " AND SD3.D3_ESTORNO <> 'S' "
    cQry += "  "
    cQry += " UNION "
    cQry += "  "
    cQry += " SELECT SD3.D3_COD AS [PRODUTO], "
    cQry += " SD3.D3_QUANT AS [QUANT], "
    cQry += " SD3.D3_LOCAL AS [ARMZ], "
    cQry += " SD3.D3_EMISSAO AS [EMISSAO], "
    cQry += " SD3.D3_OP AS [OP], "
    cQry += " SD3.D3_HIST AS [HIST], "
    cQry += " SD3.D3_USUARIO AS [USUARIO], "
    cQry += " (SD3.D3_QUANT * SB1.B1_PESPVC) AS [PVC], "
    cQry += " (SD3.D3_QUANT * SB1.B1_PESCOB) AS [COBRE], "
    cQry += " SD3.D3_CF AS [TPMOV], "
    cQry += " SD3.D3_DOC AS [DOC], "
    cQry += " SD3.D3_NUMSEQ AS [SEQ], "
    cQry += " SD3.R_E_C_N_O_ AS [REC] "
    cQry += " FROM " + RetSqlName('SD3') + " SD3 "
    cQry += " INNER JOIN " + RetSqlName('SB1') + " SB1 ON SD3.D3_COD = SB1.B1_COD AND SD3.D_E_L_E_T_ = SB1.D_E_L_E_T_ "
    cQry += " WHERE SD3.D3_FILIAL = '" + xFilial("SD3") + "' "
    cQry += " AND SD3.D3_EMISSAO >= '" + cDtIni + "' "
    cQry += " AND SD3.D3_EMISSAO <= '" + cDtFim + "' "
    cQry += " AND SD3.D3_CF IN ('DE7','DE4') "
    cQry += " AND SD3.D3_NUMSEQ NOT IN ( "
    cQry += " 						SELECT SSD3.D3_NUMSEQ "
    cQry += " 						FROM " + RetSqlName('SD3') + " SSD3 "
    cQry += " 						WHERE SSD3.D3_FILIAL = SD3.D3_FILIAL "
    cQry += " 						AND SSD3.D3_EMISSAO >= '" + cDtIni + "' "
    cQry += " 						AND SSD3.D3_EMISSAO <= '" + cDtFim + "' "
    cQry += " 						AND SSD3.D3_CF IN ('RE7','RE4') "
    cQry += " 						AND SSD3.D3_ESTORNO = SD3.D3_ESTORNO "
    cQry += " 						AND SSD3.D_E_L_E_T_ = SD3.D_E_L_E_T_  "
    cQry += " ) "
    cQry += " AND SD3.D3_ESTORNO <> 'S' "
return(cQry)

user function qryGenBlocoH(cDtFim)
    local cQry := ""

    cQry += " SELECT H.SITUACAO AS [SITUACAO], "
    cQry += " H.PRODUTO AS [PRODUTO], "
    cQry += " H.UM AS [UM], "
    cQry += " H.QUANTIDADE AS [QTD], "
    cQry += " H.VALOR_UNIT AS [VAL_UNIT], "
    cQry += " H.TOTAL AS [TOTAL], "
    cQry += " H.ARMAZEM AS [ARMAZEM], "
    cQry += " H.CLIFOR AS [CLIFOR], "
    cQry += " H.LOJA AS [LOJA], "
    cQry += " H.TPCF AS [TPCF] "
    cQry += " FROM H_" + cDtFim + "01_" + FwFilial() + " H "
    cQry += " WHERE H.D_E_L_E_T_= '' "
return(cQry)
