#include 'protheus.ch'
#include 'parmtype.ch'

user function cbcQRYWap(cOrigem, cAno, cMes)
local cQry	:= ''
	default cMes	:= ' DATEPART( month, GETDATE()) '
	default cAno	:= ' DATEPART( year, GETDATE())  '
	
	if cOrigem == 'faturamento'
		cQry += " SELECT " 
		cQry += " SF2.F2_FILIAL							AS [FILIAL], "
		cQry += " SUM(SC6.C6_CSTUNRG * SD2.D2_QUANT)	AS [CUSTO], "
		cQry += " SUM(SD2.D2_PRCVEN * SD2.D2_QUANT)		AS [VENDA]  "
		cQry += " FROM  "
		cQry +=  RetSqlName('SD2') + " SD2 WITH (NOLOCK)  "
		cQry += " INNER JOIN " + RetSqlName('SF4') + " SF4 WITH (NOLOCK) "
		cQry += " ON ''								= SF4.F4_FILIAL "
		cQry += " AND SD2.D2_TES					= SF4.F4_CODIGO "
		cQry += " AND SF4.R_E_C_N_O_				= SF4.R_E_C_N_O_ "
		cQry += " AND SD2.D_E_L_E_T_				= SF4.D_E_L_E_T_ "
		cQry += " INNER JOIN " + RetSqlName('SC6') + " SC6 WITH (NOLOCK) "
		cQry += " ON	SD2.D2_FILIAL				= SC6.C6_FILIAL "
		cQry += " AND SD2.D2_PEDIDO					= SC6.C6_NUM "
		cQry += " AND SD2.D2_ITEMPV					= SC6.C6_ITEM "
		cQry += " AND SD2.D2_COD					= SC6.C6_PRODUTO "
		cQry += " AND SC6.R_E_C_N_O_				= SC6.R_E_C_N_O_ "
		cQry += " AND SD2.D_E_L_E_T_				= SC6.D_E_L_E_T_ "
		cQry += " INNER JOIN " + RetSqlName('SF2') + " SF2 WITH (NOLOCK) "
		cQry += " ON	SD2.D2_FILIAL				= SF2.F2_FILIAL "
		cQry += " AND SD2.D2_DOC					= SF2.F2_DOC "
		cQry += " AND SD2.D2_SERIE					= SF2.F2_SERIE "
		cQry += " AND SD2.D2_CLIENTE				= SF2.F2_CLIENTE "
		cQry += " AND SD2.D2_LOJA					= SF2.F2_LOJA "
		cQry += " AND SF2.F2_FORMUL					= SF2.F2_FORMUL  "
		cQry += " AND SF2.F2_TIPO					= SF2.F2_TIPO "
		cQry += " AND SF2.R_E_C_N_O_				= SF2.R_E_C_N_O_ "
		cQry += " AND SD2.D_E_L_E_T_				= SF2.D_E_L_E_T_ "
		cQry += " INNER JOIN " + RetSqlName('SA1') + " SA1 WITH (NOLOCK) "
		cQry += " ON ''								= SA1.A1_FILIAL "
		cQry += " AND SF2.F2_CLIENTE				= SA1.A1_COD "
		cQry += " AND SF2.F2_LOJA					= SA1.A1_LOJA "
		cQry += " AND SF2.D_E_L_E_T_				= SA1.D_E_L_E_T_ "
		cQry += " INNER JOIN " + RetSqlName('SB1') + " SB1 WITH (NOLOCK) " 
		cQry += " ON  ' '		 	 = SB1.B1_FILIAL "
		cQry += " AND SD2.D2_COD 	 = SB1.B1_COD "
		cQry += " AND SB1.R_E_C_N_O_ = SB1.R_E_C_N_O_ "  
		cQry += " AND SD2.D_E_L_E_T_ = SB1.D_E_L_E_T_ "
		cQry += " WHERE "
		cQry += " SD2.D2_FILIAL		IN ('01','02','03') "
		cQry += " AND SD2.D2_CF		NOT IN ('6151','6152','6901','6124','6902') " 
		cQry += " AND DATEPART(year,CONVERT(DATETIME,SD2.D2_EMISSAO)) = "  + cAno
		cQry += " AND DATEPART(month,CONVERT(DATETIME,SD2.D2_EMISSAO)) = " + cMes 
		cQry += " AND SB1.B1_TIPO    =   'PA' "
		cQry += " AND SF4.F4_DUPLIC	=	'S' "
		cQry += " AND SF2.F2_TIPO	= 	'N' "
		cQry += " AND SF2.F2_CLIENTE NOT IN ('017449','017826','016227','017813','010188','017010','013478','015678','017011', '011248', '012677') "
		cQry += " GROUP BY SF2.F2_FILIAL "
	elseif cOrigem == 'pedido'
		cQry += " SELECT " 
		cQry += "   SC5.C5_FILIAL							AS [FILIAL], "
		cQry += " 	SUM(SC6.C6_QTDVEN * SC6.C6_PRCVEN) 		AS [VENDA], "
		cQry += " 	SUM(SC6.C6_QTDVEN * SC6.C6_CSTUNRG) 	AS [CUSTO]  "
		cQry += " FROM  "
		cQry +=  RetSqlName('SC5') + " SC5 WITH (NOLOCK) "
		cQry += " INNER JOIN " + RetSqlName('SA1') + " SA1 WITH (NOLOCK) "
		cQry += " 	ON ''					= SA1.A1_FILIAL "
		cQry += " 	AND SC5.C5_CLIENTE		= SA1.A1_COD "
		cQry += " 	AND SC5.C5_LOJACLI		= SA1.A1_LOJA "
		cQry += " 	AND SA1.R_E_C_N_O_  	= SA1.R_E_C_N_O_ "
		cQry += " 	AND SC5.D_E_L_E_T_		= SA1.D_E_L_E_T_ "
		cQry += " INNER JOIN " + RetSqlName('SC6') + " SC6 WITH (NOLOCK) "
		cQry += " 	ON SC5.C5_FILIAL		= SC6.C6_FILIAL "
		cQry += " 	AND SC5.C5_NUM			= SC6.C6_NUM "
		cQry += " 	AND SC6.C6_PRODUTO  	= SC6.C6_PRODUTO "
		cQry += " 	AND SC6.R_E_C_N_O_  	= SC6.R_E_C_N_O_ "
		cQry += " 	AND SC5.D_E_L_E_T_	= SC6.D_E_L_E_T_ "
		cQry += " INNER JOIN " + RetSqlName('SF4')+ " SF4 WITH (NOLOCK) "
		cQry += " 	ON ''					= SF4.F4_FILIAL "
		cQry += " 	AND SC6.C6_TES			= SF4.F4_CODIGO "
		cQry += " 	AND SF4.R_E_C_N_O_  	= SF4.R_E_C_N_O_ "
		cQry += " 	AND SC6.D_E_L_E_T_		= SF4.D_E_L_E_T_ "
		cQry += " INNER JOIN " + RetSqlName('SB1') + " SB1 WITH (NOLOCK) " 
		cQry += " ON  ' '		 	 	= SB1.B1_FILIAL "
		cQry += " AND SC6.C6_PRODUTO 	= SB1.B1_COD "
		cQry += " AND SB1.R_E_C_N_O_ 	= SB1.R_E_C_N_O_ "  
		cQry += " AND SC6.D_E_L_E_T_ 	= SB1.D_E_L_E_T_ "	
		cQry += " WHERE "
		cQry += " 	SC5.C5_FILIAL			IN	('01','02','03') "
		cQry += " 	AND DATEPART(YEAR, CONVERT(DATETIME,SC5.C5_EMISSAO)) = " + cAno 
		cQry += " 	AND DATEPART(MONTH,CONVERT(DATETIME,SC5.C5_EMISSAO)) = " + cMes
		cQry += "   AND SB1.B1_TIPO    =   'PA' "
		cQry += " 	AND SC5.C5_TIPO			= 	'N' "
		cQry += " 	AND SA1.A1_VISVEND		<> 'N' "
		cQry += " 	AND SC6.C6_CF			NOT IN ('6151','6152','6901','6124','6902') " 
		cQry += " 	AND SF4.F4_DUPLIC		=	'S' "
		cQry += " 	GROUP BY SC5.C5_FILIAL "
	endif
	
return(cQry)